# VFX Launcher Network Configuration

[network]
# Server IP address (the machine running the application)
server_ip = "127.0.0.1"
server_port = 8080

[database]
# Database mode: "network" or "local"
mode = "network"
# Network database path - using the mounted volume
network_path = "/Volumes/Naboo/DB"
# Windows mapped drive equivalent
windows_drive = "U:"

[paths]
# Base network path for projects - using the mounted volume
network_base = "/Volumes/Naboo"
# Windows mapped drive for network path
windows_mapped_drive = "U:"
